[theme]

# Primary accent for interactive elements
primaryColor = '#C55B11'

# Background color for the main content area
backgroundColor = '#222A37'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#205867'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
